export const Saucedemo_Locators = {
    loginLogo: (page) => page.locator('.login_logo'),
    userName: (page) => page.locator('#user-name'),
    userPassword: (page) => page.locator('#password'),
    loginBtn: (page) => page.locator('#login-button'),
    hamburger: (page) => page.locator('#react-burger-menu-btn'),
    appLogo: (page) => page.locator('.app_logo'),
    shoppingCart: (page) => page.locator('#shopping_cart_container'),
    title: (page) => page.locator('.title'),
    dropdown: (page) => page.locator('.product_sort_container'),
    inventoryItem: (page) => page.locator('.inventory_item'),
    addToCart: (page) => page.locator('#add-to-cart-sauce-labs-backpack'),
    cartIconNotification: (page) => page.locator('.shopping_cart_badge'),
    removeBtn: (page) => page.locator('#remove-sauce-labs-backpack'),
    itemName: (page) => page.locator('.inventory_item_name '),
    itemPrice: (page) => page.locator(`.inventory_item_price`),
    footer: (page) => page.locator('.footer'),
    socialTwitter: (page) => page.locator('.social_twitter'),
    socialFacebook: (page) => page.locator('.social_facebook'),
    socialLinkedin: (page) => page.locator('.social_linkedin'),
    menu: (page) => page.locator('.bm-menu'),
    closeIcon: (page) => page.locator('#react-burger-cross-btn'),
    headerSecondaryName: (page) => page.locator('.header_secondary_container'),
    cartQtyLabel: (page) => page.locator(".cart_quantity_label"),
    description: (page) => page.locator(".cart_desc_label"),
    itemQty: (page) => page.locator(".cart_quantity"),
    itemDescription: (page) => page.locator('.inventory_item_desc'),
    continueShopping: (page) => page.locator('#continue-shopping'),
    checkout: (page) => page.locator("#checkout"),
    firstName: (page) => page.locator('#first-name'),
    lastName: (page) => page.locator('#last-name'),
    postalCOde: (page) => page.locator('#postal-code'),
    continueBTn: (page) => page.locator('#continue'),
    summaryInfoLabel: (page) => page.locator(`div[data-test='payment-info-label']`),
    paymentInfoValue: (page) => page.locator(`div[data-test='payment-info-value']`),
    shippingInfo: (page) => page.locator(`div[data-test='shipping-info-label']`),
    shippingInfoValue:(page) => page.locator(`div[data-test='shipping-info-value']`),
    totalInfoLabel: (page) => page.locator(`div[data-test='total-info-label']`),
    subTotalItem: (page) => page.locator(`.summary_subtotal_label`),
    taxLabel: (page) => page.locator(`.summary_tax_label`),
    summaryTotalLabel: (page) => page.locator(`.summary_total_label`),
    finishBtn: (page) => page.locator(`#finish`),
    tickIcon: (page) => page.locator(`.pony_express`),
    completeHeader: (page) => page.locator(`.complete-header`),
    completeText: (page) => page.locator(`.complete-text`),
    backToProduct: (page) => page.locator(`#back-to-products`),
    sidebarLogout: (page) => page.locator(`#logout_sidebar_link`),

};
